### GET all tasks
GET http://localhost:4000/api/tasks

### GET task by ID
GET http://localhost:4000/api/tasks/1

### POST create task
POST http://localhost:4000/api/tasks
Content-Type: application/json

{
  "title": "title",
  "description": "hola",
  "iduser": "1"
}

### PATCH update task 
PATCH http://localhost:4000/api/tasks/1
Content-Type: application/json

{
  "title" :"tituloo"
}

### PATCH update estado task completado 
PATCH http://localhost:4000/api/tasks/1/complete
Content-Type: application/json